[litex]
type = "github"
github_user = "enjoy-digital"
github_repo = "litex"
git_revision = "4dabf0a330fd2454c1f9db4c9c978aa2bd754b5f"

[litex-boards]
type = "github"
github_user = "litex-hub"
github_repo = "litex-boards"
git_revision = "3308b6ddf35705377d2996fd2519c55ad65936c4"

[liteeth]
type = "github"
github_user = "enjoy-digital"
github_repo = "liteeth"
git_revision = "97dccdb294fa2081536f26f4ef6235c004007432"

[litedram]
type = "github"
github_user = "enjoy-digital"
github_repo = "litedram"
git_revision = "6c8df7cc7be2f88e2d78d6282ada4213918de477"

[litehyperbus]
type = "github"
github_user = "litex-hub"
github_repo = "litehyperbus"
git_revision = "76454e4c0c304a34b9915722de750887c3abbe89"

[liteiclink]
type = "github"
github_user = "enjoy-digital"
github_repo = "liteiclink"
git_revision = "e09593f3da7c8744d53c26b54bf12d691a5ee255"

[litepcie]
type = "github"
github_user = "enjoy-digital"
github_repo = "litepcie"
git_revision = "0aa1a629b6468ffeb49e0428ef1d39ec80491d71"

[litescope]
type = "github"
github_user = "enjoy-digital"
github_repo = "litescope"
git_revision = "457f0875db0c1a0ff0e20659fe81b5bf696875d4"

[litesdcard]
type = "github"
github_user = "enjoy-digital"
github_repo = "litesdcard"
git_revision = "15955d88ad2390dfa46f4846f7fc22bd642738db"

[litespi]
type = "github"
github_user = "litex-hub"
github_repo = "litespi"
git_revision = "63c815fe7c0c28b132a2407d836b7d8f80ea7a61"

[litevideo]
type = "github"
github_user = "enjoy-digital"
github_repo = "litevideo"
git_revision = "41f30143075ece3fff5c33a332ed067d1837cbb3"

[pythondata-cpu-vexriscv]
type = "github"
github_user = "litex-hub"
github_repo = "pythondata-cpu-vexriscv"
git_revision = "a36d99eeea984c261e16b744fc1d287c81099777"

[pythondata-cpu-vexriscv_smp]
type = "github"
github_user = "litex-hub"
github_repo = "pythondata-cpu-vexriscv_smp"
git_revision = "98d6db6d44e0b543715ac3af4fb6fa415284fb24"

[pythondata-misc-tapcfg]
type = "github"
github_user = "litex-hub"
github_repo = "pythondata-misc-tapcfg"
git_revision = "fbcb02422940bbb97c492f0c970959d262b33632"

[pythondata-software-compiler_rt]
type = "github"
github_user = "litex-hub"
github_repo = "pythondata-software-compiler_rt"
git_revision = "fcb03245613ccf3079cc833a701f13d0beaae09d"

[pythondata-cpu-serv]
type = "github"
github_user = "litex-hub"
github_repo = "pythondata-cpu-serv"
git_revision = "cdede3b5e35e0c8c385ff10d783905d95cd864ab"

[pythondata-software-picolibc]
type = "github"
github_user = "litex-hub"
github_repo = "pythondata-software-picolibc"
git_revision = "a5e11229885a87083ec54034f8d693ba52ea2718"

[valentyusb-hw_cdc_eptri]
type = "github"
github_user = "litex-hub"
github_repo = "valentyusb"
git_revision = "0b534ccfccfcdcb7a5db219743f0c0b20e5ec412"
git_branch = "hw_cdc_eptri"
