[litex]
type = "github"
github_user = "enjoy-digital"
github_repo = "litex"
git_revision = "6164a55c6b54f1d9a24cd828ac90d827249fe262"

[litex-boards]
type = "github"
github_user = "litex-hub"
github_repo = "litex-boards"
git_revision = "1b22061e93b2add0132cfbcd10ca0e9977a163b2"

[liteeth]
type = "github"
github_user = "enjoy-digital"
github_repo = "liteeth"
git_revision = "7d24ac33ae5c8109c48465cf676101b692cf6453"

[litedram]
type = "github"
github_user = "enjoy-digital"
github_repo = "litedram"
git_revision = "6bce3a2587f0d71d72ef2ec9594ae6acd72ec782"

[litehyperbus]
type = "github"
github_user = "litex-hub"
github_repo = "litehyperbus"
git_revision = "76454e4c0c304a34b9915722de750887c3abbe89"

[liteiclink]
type = "github"
github_user = "enjoy-digital"
github_repo = "liteiclink"
git_revision = "e0af9e573e6e8054becbb5ce8357eec26b759d15"

[litepcie]
type = "github"
github_user = "enjoy-digital"
github_repo = "litepcie"
git_revision = "ab7be7185bbd5d02f33bc1b0d2a1e78d75c47f6e"

[litescope]
type = "github"
github_user = "enjoy-digital"
github_repo = "litescope"
git_revision = "976656b5194db2cdf6c3257c5975e4fa1233f859"

[litesdcard]
type = "github"
github_user = "enjoy-digital"
github_repo = "litesdcard"
git_revision = "b243b3be4bd2cc038cc2b019c8795bdf5d86d03a"

[litespi]
type = "github"
github_user = "litex-hub"
github_repo = "litespi"
git_revision = "3a0651d91248a8547c13e2365733f02fd6789fb8"

[litevideo]
type = "github"
github_user = "enjoy-digital"
github_repo = "litevideo"
git_revision = "41f30143075ece3fff5c33a332ed067d1837cbb3"

[pythondata-cpu-vexriscv]
type = "github"
github_user = "litex-hub"
github_repo = "pythondata-cpu-vexriscv"
git_revision = "1979a644dbe64d8d32dfbdd970dccee6add63723"

[pythondata-cpu-vexriscv_smp]
type = "github"
github_user = "litex-hub"
github_repo = "pythondata-cpu-vexriscv_smp"
git_revision = "1f8f8bb49538663759f043e83ebae311132fc3e5"

[pythondata-misc-tapcfg]
type = "github"
github_user = "litex-hub"
github_repo = "pythondata-misc-tapcfg"
git_revision = "fbcb02422940bbb97c492f0c970959d262b33632"

[pythondata-software-compiler_rt]
type = "github"
github_user = "litex-hub"
github_repo = "pythondata-software-compiler_rt"
git_revision = "fcb03245613ccf3079cc833a701f13d0beaae09d"

[pythondata-cpu-serv]
type = "github"
github_user = "litex-hub"
github_repo = "pythondata-cpu-serv"
git_revision = "cdede3b5e35e0c8c385ff10d783905d95cd864ab"

[pythondata-software-picolibc]
type = "github"
github_user = "litex-hub"
github_repo = "pythondata-software-picolibc"
git_revision = "a5e11229885a87083ec54034f8d693ba52ea2718"

[valentyusb-hw_cdc_eptri]
type = "github"
github_user = "litex-hub"
github_repo = "valentyusb"
git_revision = "0b534ccfccfcdcb7a5db219743f0c0b20e5ec412"
git_branch = "hw_cdc_eptri"

[pythondata-misc-usb_ohci]
type = "github"
github_user = "litex-hub"
github_repo = "pythondata-misc-usb_ohci"
git_revision = "1f9c77314d3b91fe3194245c3e3197a075803199"
